<?php
class TemplateToaster_Theme_Options_Dynamic
{
public $sections;
public $checkboxes;
public $contactvar;
public $settings;

 /*** Construct ***/
public function __construct()
{
// This will keep track of the checkbox options for the validate_settings function.
$this->checkboxes = array();
$this->settings = array();
$this->get_dynamic_options();
$this->sections['header'] = __('Header', 'Cloth-Store');
$this->sections['postcontent'] = __('Post/Content', 'Cloth-Store');
$this->sections['footer'] = __('Footer', 'Cloth-Store');
$this->sections['colors'] = __('Colors', 'Cloth-Store');
$this->sections['generaloptions'] = __('General', 'Cloth-Store');
$contactvar=get_option('contact_form',"ttr_test");
if( $contactvar == "ttr_test") {
$adminmail=get_option('admin_email');
$default=array(0=>array('ttr_email'=>''),1=>array('ttr_captcha_public_key'=>''),2=>array('ttr_captcha_private_key'=>''),3=>array('ttr_contact_us_error_message'=>'Message was not sent. Try Again.'),4=>array('ttr_contact_us_success_message'=>'Thanks! Your message has been sent.'));
update_option( 'contact_form', $default );
}
}
public function get_dynamic_options()
{
$menulogo = get_template_directory_uri() . '/menulogo.png';
$headerlogo = get_template_directory_uri() . '/logo.png';
$headerrss = get_template_directory_uri().'/images/headerrss.png';
$headerfacebook = get_template_directory_uri().'/images/headerfacebook.png';
$headerlinkedin = get_template_directory_uri().'/images/headerlinkedin.png';
$headertwitter = get_template_directory_uri().'/images/headertwitter.png';
$headerinstagram = get_template_directory_uri() . '/images/headerinstagram.png';
$footerrss = get_template_directory_uri().'/images/footerrss.png';
$footertwitter = get_template_directory_uri().'/images/footertwitter.png';
$footerinstagram = get_template_directory_uri() . '/images/footerinstagram.png';
$footerfacebook = get_template_directory_uri().'/images/footerfacebook.png';
$footerlinkedin = get_template_directory_uri().'/images/footerlinkedin.png';
$favicon = get_template_directory_uri().'/favicon.ico';
$copyright_url = home_url();
$headeryoutube = get_template_directory_uri().'/images/headeryoutube.png';
$footeryoutube = get_template_directory_uri().'/images/footeryoutube.png';
$facebook_url = 'https://www.facebook.com/TemplateToaster';
$linkedin_url = 'https://www.linkedin.com/company/templatetoaster/';
$twitter_url = 'https://twitter.com/templatetoaster';
$instagram_url = 'https://www.instagram.com/templatetoaster/';
$youtube_url = 'https://www.youtube.com/templatetoaster';
$footer_facebook_url = 'https://www.facebook.com/TemplateToaster';
$footer_linkedin_url = 'https://www.linkedin.com/company/templatetoaster/';
$footer_twitter_url = 'https://twitter.com/templatetoaster';
$footer_instagram_url = 'https://www.instagram.com/templatetoaster/';
$footer_youtube_url = 'https://www.youtube.com/templatetoaster';
/* Color Settings */

$this->settings['ttr_designedby'] = array(
'title' => __('Footer Designed By Color', 'Cloth-Store'),
'desc' => __('Choose footer Designed By color', 'Cloth-Store'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_designedbylink'] = array(
'title' => __('Footer Designed By Link Color', 'Cloth-Store'),
'desc' => __('Choose footer Designed By link color', 'Cloth-Store'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_blockheading'] = array(
'title' => __('Block Heading Color', 'Cloth-Store'),
'desc' => __('Choose block heading color', 'Cloth-Store'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_post_title_color'] = array(
'title' => __('Page/Post Title Normal Color', 'Cloth-Store'),
'desc' => __('Choose Page/Post title normal color', 'Cloth-Store'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
$this->settings['ttr_post_title_hover_color'] = array(
'title' => __('Post Title Hover Color', 'Cloth-Store'),
'desc' => __('Choose post title hover color', 'Cloth-Store'),
'std' => '',
/*'class' => 'colorwell',*/
'type' => 'colorpicker',
'section' => 'colors');
/* Post/Content Settings */
$this->settings['ttr_featured_post'] = array(
'title' => __('Number of Featured Posts', 'Cloth-Store'),
'desc' => __('How many posts would you like to be displayed as featured on the front page?', 'Cloth-Store'),
'std' => '1',
'pattern' => '\d+',
'type' => 'text',
'section' => 'postcontent');
$this->settings['ttr_post_layout'] = array(
'title' => __('Number of Columns', 'Cloth-Store'),
'desc' => __('How many columns would you like to display the posts after featured posts', 'Cloth-Store'),
'std' => '4',
'pattern' => '\d+',
'type' => 'text',
'section' => 'postcontent');
$this->settings['ttr_page_breadcrumb'] = array(
'title' => __('Show Breadcrumbs On Page', 'Cloth-Store'),
'desc' => __('Check this box if you would like to ENABLE the Breadcrumbs On Page', 'Cloth-Store'),
'std' => 0,
'type' => 'checkbox',
'section' => 'postcontent');
$this->settings['ttr_post_breadcrumb'] = array(
'title' => __('Show Breadcrumbs On Post', 'Cloth-Store'),
'desc' => __('Check this box if you would like to ENABLE the Breadcrumbs On Post', 'Cloth-Store'),
'std' => 0,
'type' => 'checkbox',
'section' => 'postcontent');
$this->settings['ttr_breadcrumb_text'] = array(
'title' => __('Breadcrumbs Prefix', 'Cloth-Store'),
'desc' => __('Choose breadcrumbs text', 'Cloth-Store'),
'std' => '',
'type' => 'text',
'section' => 'postcontent');
$this->settings['ttr_breadcrumb_text_separator'] = array(
'title' => __('Breadcrumbs Separator', 'Cloth-Store'),
'desc' => __('Set your Breadcrumbs separator', 'Cloth-Store'),
'std' => '',
'type' => 'text',
'section' => 'postcontent');
 /*** Header ***/
/* Footer Settings */

$this->settings['ttr_font_size_designedby'] = array(
'title' => __('Footer Designed By Font Size', 'Cloth-Store'),
'desc' => __('Enter the font size of Footer Designed By', 'Cloth-Store'),
'std' => '',
'type' => 'text',
'section' => 'footer');
$this->settings['ttr_deisgnedby_text'] = array(
'title' => __('Footer Designed By text', 'Cloth-Store'),
'desc' => __('Enter Footer Designed By text', 'Cloth-Store'),
'std' => 'Designed With TemplateToaster',
'type' => 'text',
'section' => 'footer');
$this->settings['ttr_font_size_designedbylink'] = array(
'title' => __('Footer Designed By Link Font Size', 'Cloth-Store'),
'desc' => __('Enter the font size of Footer Designed By Link', 'Cloth-Store'),
'std' => '',
'type' => 'text',
'section' => 'footer');
$this->settings['ttr_designedby_link'] = array(
'title' => __('Footer Designed By Link ', 'Cloth-Store'),
'desc' => __('Enter the text of Footer Designed By Link', 'Cloth-Store'),
'std' => 'WordPress Theme',
'type' => 'text',
'section' => 'footer');
$this->settings['ttr_designedby_link_url'] = array(
'title' => __('Footer Designed By Link URL', 'Cloth-Store'),
'desc' => __('Enter footer designed by link URL, must be a valid URL(containing http://)', 'Cloth-Store'),
'std' =>'https://templatetoaster.com',
'type' => 'text',
'section' => 'footer');
/** General Options **/

$this->settings['ttr_theme_bootstrap_enable'] = array(
'title' => __('Enable Theme Bootstrap Javascipt', 'Cloth-Store'),
'desc' => __('ENABLE/DISABLE Theme Bootstrap Javascipt', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_google_analytics'] = array(
'title' => __('Google Analytics', 'Cloth-Store'),
'desc' => __('Text Box for google analytics', 'Cloth-Store'),
'std' => '',
'type' => 'textarea',
'section' => 'generaloptions');
$this->settings['ttr_google_analytics_enable'] = array(
'title' => __('Enable Google Analytics', 'Cloth-Store'),
'desc' => __('ENABLE/DISABLE Google Analytics', 'Cloth-Store'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_custom_style'] = array(
'title' => __('Custom CSS', 'Cloth-Store'),
'desc' => __('Text Box for custom css', 'Cloth-Store'),
'std' => '',
'type' => 'textarea',
'section' => 'generaloptions');
$this->settings['ttr_all_page_title'] = array(
'title' => __('Display All Page Titles', 'Cloth-Store'),
'desc' => __('On/Off the page title', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_all_post_title'] = array(
'title' => __('Display All Post Titles', 'Cloth-Store'),
'desc' => __('On/Off the post title', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_remove_date'] = array(
'title' => __('Display Post Date', 'Cloth-Store'),
'desc' => __('On/Off the post date', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_remove_author_name'] = array(
'title' => __('Display Author Name', 'Cloth-Store'),
'desc' => __('On/Off the author name', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_remove_post_category'] = array(
'title' => __('Show Post Category', 'Cloth-Store'),
'desc' => __('Show Post Category', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post_navigation_above'] = array(
'title' => __('Display Navigation above the posts', 'Cloth-Store'),
'desc' => __('Show/Hide navigation above the posts', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post_navigation_below'] = array(
'title' => __('Display Navigation below the posts', 'Cloth-Store'),
'desc' => __('Show/Hide navigation below the posts', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_older_newer_posts_above'] = array(
'title' => __('Display Older/Newer Posts Link  above the posts', 'Cloth-Store'),
'desc' => __('Show/Hide Older/Newer Posts Link above the posts', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_older_newer_posts_below'] = array(
'title' => __('Display Older/Newer Posts Link below the posts', 'Cloth-Store'),
'desc' => __('Show/Hide Older/Newer Posts Link below the posts', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post_navigation_post'] = array(
'title' => __('Display Post Navigation', 'Cloth-Store'),
'desc' => __('Show/Hide post navigation', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post_category_post'] = array(
'title' => __('Display Post Category', 'Cloth-Store'),
'desc' => __('Show/Hide post Category', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_previous_next_links'] = array(
'title' => __('Display Previous/next Posts Link', 'Cloth-Store'),
'desc' => __('Show/Hide Previous/next  Posts Link', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_pagination_link_posts_above'] = array(
'title' => __('Display Pagination Link Of Post Pages above the posts', 'Cloth-Store'),
'desc' => __('Show/Hide Pagination Link Of Post Pages above the posts', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_pagination_link_posts_below'] = array(
'title' => __('Display Pagination Link Of Post Pages below the posts', 'Cloth-Store'),
'desc' => __('Show/Hide Pagination Link Of Post Pages  below the posts', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_comments_closed_text'] = array(
'title' => __('Display Comments are closed ', 'Cloth-Store'),
'desc' => __('Show/Hide Comments are closed', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_comments_list'] = array(
'title' => __('Display Comments List', 'Cloth-Store'),
'desc' => __('Show/Hide Comments ', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_comments_form'] = array(
'title' => __('Display Comments Form', 'Cloth-Store'),
'desc' => __('Show/Hide Comment form ', 'Cloth-Store'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_comment_list_form'] = array(
'title' => __('Show Comments list', 'Cloth-Store'),
'desc' => __('Check this box to show comment form below comments list.', 'Cloth-Store'),
'type' => 'radio',
'std' => 'choice1',
'choices' => array(
'choice1' => __('Above Comment Form', 'Cloth-Store'),
'choice2' => __('Below Comment Form', 'Cloth-Store')
),
'section' => 'generaloptions');
$this->settings['ttr_avatar_size'] = array(
'title' => __('Avatar Size', 'Cloth-Store'),
'desc' => __('Set Avatar size ', 'Cloth-Store'),
'std' => '',
'pattern' => '\d+',
'type' => 'text',
'section' => 'generaloptions');
$this->settings['ttr_back_to_top'] = array(
'title' => __('Display Back To Top Button', 'Cloth-Store'),
'desc' => __('on/off the back to top button', 'Cloth-Store'),
'std' => 1,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_icon_back_to_top'] = array(
'title' => __('Choose icon for Back To Top Button', 'Cloth-Store'),
'desc' => __('Choose icon for back to top button', 'Cloth-Store'),
'std' => '',
'type' => 'media',
'section' => 'generaloptions');
$this->settings['ttr_read_more'] = array(
'title' => __('Read More Text', 'Cloth-Store'),
'desc' => __('Change Text For Read More Link', 'Cloth-Store'),
'std' => __('Continue Reading', 'Cloth-Store'),
'type' => 'text',
'section' => 'generaloptions');
$this->settings['ttr_read_more_button'] = array(
'title' => __('Display Button For Read More', 'Cloth-Store'),
'desc' => __('Enable/Disable the Read More button', 'Cloth-Store'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_post1_enable'] = array(
'title' => __('Read more on all posts', 'Cloth-Store'),
'desc' => __('on/off the Read More on all posts', 'Cloth-Store'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
$this->settings['ttr_read_length'] = array(
'title' => __('Word Count', 'Cloth-Store'),
'desc' => __('After how many words you need read more', 'Cloth-Store'),
'std' => '',
'pattern' => '\d+',
'type' => 'text',
'section' => 'generaloptions');
$this->settings['ttr_search_icon_enable'] = array(
'title' => __('Display Search Icon In Search Widget', 'Cloth-Store'),
'desc' => __('Display/Hide Search Icon', 'Cloth-Store'),
'std' => 0,
'type' => 'checkbox',
'section' => 'generaloptions');
}
}
?>
